apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.microservice.name }}
  namespace: monitoring
  labels:
    release: prometheus # matches kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      app: {{ .Values.microservice.name }}
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 15ss