microservice: ## general service details
  name: grade-submission-portal
  namespace: grade-submission
  replicas: 3


workload:  ## container specific configurations
  image: rchapagain/cicdapp:50ec0af
  port: 8085   #5001
  
  resources:
    memory: "512Mi"
    cpu: "200m"
  livenessDelay: 15

env:   ## environment variables
  GRADE_SERVICE_HOST: grade-submission-api


## upgrade to include host for ingress
healthcheck:
  livenessPath:  /actuator/health/liveness                 #/healthz
  readinessPath: /actuator/health/readiness                   #/readyz